config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
   :controllers => {
    :registrations => "users/registrations"
   }

  resources :races

  resources :grandprix_circuits
  resources :circuits
  resources :grandprixes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'

  post 'new_grandprix_circuit', to: 'grandprix_circuits#new'

  authenticated :user do
    root 'grandprixes#index', as: :authenticated_root
  end
end

app/models/grandprix_circuit.rb
class GrandprixCircuit < ApplicationRecord
  belongs_to :grandprix
  belongs_to :circuit
  has_one :grandprix_circuit

  validates :grandprix_id, uniqueness: { scope: :circuit_id }
end

app/controllers/grandprix_circuits_controller.rb
class GrandprixCircuitsController < ApplicationController
  before_action :set_grandprix_circuit, only: %i[ show edit update destroy ]

  # GET /grandprix_circuits or /grandprix_circuits.json
  def index
    @grandprix_circuits = GrandprixCircuit.all
  end

  # GET /grandprix_circuits/1 or /grandprix_circuits/1.json
  def show
  end

  # GET /grandprix_circuits/new
  def new
    @grandprix_circuit = GrandprixCircuit.new()
  end

  # GET /grandprix_circuits/1/edit
  def edit
  end

  # POST /grandprix_circuits or /grandprix_circuits.json
  def create
    @grandprix_circuit = GrandprixCircuit.new(grandprix_circuit_params)

    respond_to do |format|
      if @grandprix_circuit.save
        format.html { redirect_to grandprix_circuit_url(@grandprix_circuit), notice: "Grandprix circuit was successfully created." }
        format.json { render :show, status: :created, location: @grandprix_circuit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grandprix_circuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grandprix_circuits/1 or /grandprix_circuits/1.json
  def update
    respond_to do |format|
      if @grandprix_circuit.update(grandprix_circuit_params)
        format.html { redirect_to grandprix_circuit_url(@grandprix_circuit), notice: "Grandprix circuit was successfully updated." }
        format.json { render :show, status: :ok, location: @grandprix_circuit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grandprix_circuit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grandprix_circuits/1 or /grandprix_circuits/1.json
  def destroy
    @grandprix_circuit.destroy

    respond_to do |format|
      format.html { redirect_to grandprix_circuits_url, notice: "Grandprix circuit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grandprix_circuit
      @grandprix_circuit = GrandprixCircuit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grandprix_circuit_params
      params.require(:grandprix_circuit).permit(:grandprix_id, :circuit_id)
    end
end

app/helpers/grandprix_circuits_helper.rb
module GrandprixCircuitsHelper
end

app/views/grandprix_circuits/_form.html.erb
<%= form_with(model: grandprix_circuit) do |form| %>
  <% if grandprix_circuit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grandprix_circuit.errors.count, "error") %> prohibited this grandprix_circuit from being saved:</h2>

      <ul>
        <% grandprix_circuit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :grandprix_id, value: params[:grandprix_id] %>

  <div class="field">
    <%= form.label :circuit %>
    <%= form.select :circuit_id, options_for_select(Circuit.all.pluck(:name, :id)) %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grandprix_circuits/edit.html.erb
<h1>Editing Grandprix Circuit</h1>

<%= render 'form', grandprix_circuit: @grandprix_circuit %>

<%= link_to 'Show', @grandprix_circuit %> |
<%= link_to 'Back', grandprix_circuits_path %>

app/views/grandprix_circuits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grandprix Circuits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grandprix_circuits.each do |grandprix_circuit| %>
      <tr>
        <td><%= grandprix_circuit.name %></td>
        <td><%= grandprix_circuit.description %></td>
        <td><%= link_to 'Show', grandprix_circuit %></td>
        <td><%= link_to 'Edit', edit_grandprix_circuit_path(grandprix_circuit) %></td>
        <td><%= link_to 'Destroy', grandprix_circuit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grandprix Circuit', new_grandprix_circuit_path %>

app/views/grandprix_circuits/new.html.erb
<h1>New Grandprix Circuit</h1>

<%= render 'form', grandprix_circuit: @grandprix_circuit %>

<%= link_to 'Back', grandprix_circuits_path %>

app/views/grandprix_circuits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @grandprix_circuit.circuit.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @grandprix_circuit.circuit.description %>
</p>

<%= link_to "Add Race", new_race_path(grandprix_circuit_id: @grandprix_circuit.id) %>

<%= link_to 'Edit', edit_grandprix_circuit_path(@grandprix_circuit) %> |
<%= link_to 'Back', grandprix_circuits_path %>