config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
   :controllers => {
    :registrations => "users/registrations"
   }

  resources :races

  resources :grandprix_circuits
  resources :circuits
  resources :grandprixes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'

  post 'new_grandprix_circuit', to: 'grandprix_circuits#new'

  authenticated :user do
    root 'grandprixes#index', as: :authenticated_root
  end
end

app/models/circuit.rb
class Circuit < ApplicationRecord
  has_many :grandprix_circuits, dependent: :destroy
  attribute :grandprix_id
  # has_one_attached :image
end

app/controllers/circuits_controller.rb
class CircuitsController < ApplicationController
  before_action :set_circuit, only: [:show, :edit, :update, :destroy]

  # GET /circuits or /circuits.json
  def index
    @circuits = Circuit.all
  end

  # GET /circuits/1 or /circuits/1.json
  def show
  end

  # GET /circuits/new
  def new
    @circuit = Circuit.new
  end

  # GET /circuits/1/edit
  def edit
  end

  # POST /circuits or /circuits.json
  def create
    @circuit = Circuit.new(circuit_params)
    respond_to do |format|
      if @circuit.save
        format.html { redirect_to @circuit, notice: 'Circuit was successfully created.' }
        format.json { render :show, status: :created, location: @circuit }
      else
        format.html { render :new }
        format.json { render json: @circuit.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /circuits/1 or /circuits/1.json
  def update
    respond_to do |format|
      if @circuit.update(circuit_params)
        format.html { redirect_to circuit_url(@circuit), notice: "Circuit was successfully updated." }
        format.json { render :show, status: :ok, location: @circuit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @circuit.errors, status: :unprocessable_entity }
      end
    end
  end






  # DELETE /circuits/1 or /circuits/1.json
  def destroy
    @circuit.destroy

    respond_to do |format|
      format.html { redirect_to circuits_url, notice: "Circuit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circuit
      @circuit = Circuit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def circuit_params
      params.require(:circuit).permit(:name, :description)
    end
end

app/helpers/circuits_helper.rb
module CircuitsHelper
end

app/views/circuits/_form.html.erb
<%= form_with(model: circuit) do |form| %>
  <% if circuit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(circuit.errors.count, "error") %> prohibited this circuit from being saved:</h2>

      <ul>
        <% circuit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/circuits/edit.html.erb
<h1>Editing Circuit</h1>

<%= render 'form', circuit: @circuit %>

<%= link_to 'Show', @circuit %> |
<%= link_to 'Back', circuits_path %>

app/views/circuits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Circuits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @circuits.each do |circuit| %>
      <tr>
        <td><%= circuit.name %></td>
        <td><%= circuit.description %></td>
        <td><%= link_to 'Show', circuit %></td>
        <td><%= link_to 'Edit', edit_circuit_path(circuit) %></td>
        <td><%= link_to 'Destroy', circuit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Circuit', new_circuit_path %>

app/views/circuits/new.html.erb
<h1>New Circuit</h1>

<%= render 'form', circuit: @circuit %>

<%= link_to 'Back', circuits_path %>

app/views/circuits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @circuit.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @circuit.description %>
</p>

<%= link_to 'Edit', edit_circuit_path(@circuit) %> |
<%= link_to 'Back', circuits_path %>