config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
   :controllers => {
    :registrations => "users/registrations"
   }

  resources :races

  resources :grandprix_circuits
  resources :circuits
  resources :grandprixes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'

  post 'new_grandprix_circuit', to: 'grandprix_circuits#new'

  authenticated :user do
    root 'grandprixes#index', as: :authenticated_root
  end
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :grandprix_circuit
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: %i[ show edit update destroy ]

  # GET /races or /races.json
  def index
    @races = Race.all
  end

  # GET /races/1 or /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races or /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to race_url(@race), notice: "Race was successfully created." }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1 or /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to race_url(@race), notice: "Race was successfully updated." }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1 or /races/1.json
  def destroy
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url, notice: "Race was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def race_params
      params.require(:race).permit(:grandprix_circuit_id, :p1, :p2, :p3, :p4, :p5, :p6, :p7, :p8, :p9, :p10, :p11, :p12, :p13, :p14, :p15, :p16, :p17, :p18, :p19, :p20)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_with(model: race) do |form| %>
  <% if race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
        <% race.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :grandprix_circuit_id, value: params[:grandprix_circuit_id] %>

  <div class="field">
    <%= form.label :p1 %>
    <%= form.select :p1, options_for_select(User.all.pluck(:name, :id), include_blank: "Select One") %>
  </div>

  <div class="field">
    <%= form.label :p2 %>
    <%= form.select :p2, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p3 %>
    <%= form.select :p3, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p4 %>
    <%= form.select :p4, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p5 %>
    <%= form.select :p5, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p6 %>
    <%= form.select :p6, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p7 %>
    <%= form.select :p7, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p8 %>
    <%= form.select :p8, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p9 %>
    <%= form.select :p9, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p10 %>
    <%= form.select :p10, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p11 %>
    <%= form.select :p11, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p12 %>
    <%= form.select :p12, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p13 %>
    <%= form.select :p13, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p14 %>
    <%= form.select :p14, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p15 %>
    <%= form.select :p15, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p16 %>
    <%= form.select :p16, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p17 %>
    <%= form.select :p17, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p18 %>
    <%= form.select :p18, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p19 %>
    <%= form.select :p19, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="field">
    <%= form.label :p20 %>
    <%= form.select :p20, options_for_select(User.all.pluck(:name, :id), :include_blank => true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Races</h1>

<table>
  <thead>
    <tr>
      <th>Grandprix circuit</th>
      <th>P1</th>
      <th>P2</th>
      <th>P3</th>
      <th>P4</th>
      <th>P5</th>
      <th>P6</th>
      <th>P7</th>
      <th>P8</th>
      <th>P9</th>
      <th>P10</th>
      <th>P11</th>
      <th>P12</th>
      <th>P13</th>
      <th>P14</th>
      <th>P15</th>
      <th>P16</th>
      <th>P17</th>
      <th>P18</th>
      <th>P19</th>
      <th>P20</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.grandprix_circuit_id %></td>
        <td><%= race.p1 %></td>
        <td><%= race.p2 %></td>
        <td><%= race.p3 %></td>
        <td><%= race.p4 %></td>
        <td><%= race.p5 %></td>
        <td><%= race.p6 %></td>
        <td><%= race.p7 %></td>
        <td><%= race.p8 %></td>
        <td><%= race.p9 %></td>
        <td><%= race.p10 %></td>
        <td><%= race.p11 %></td>
        <td><%= race.p12 %></td>
        <td><%= race.p13 %></td>
        <td><%= race.p14 %></td>
        <td><%= race.p15 %></td>
        <td><%= race.p16 %></td>
        <td><%= race.p17 %></td>
        <td><%= race.p18 %></td>
        <td><%= race.p19 %></td>
        <td><%= race.p20 %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grandprix circuit:</strong>
  <%= @race.grandprix_circuit_id %>
</p>

<p>
  <strong>P1:</strong>
  <%= User.find(@race.p1).name %>
</p>

<p>
  <strong>P2:</strong>
  <%= User.find(@race.p2).name %>
</p>

<p>
  <strong>P3:</strong>
  <%= User.find(@race.p3).name %>
</p>

<p>
  <strong>P4:</strong>
  <%= User.find(@race.p4).name %>
</p>

<p>
  <strong>P5:</strong>
  <%= User.find(@race.p5).name %>
</p>

<p>
  <strong>P6:</strong>
  <%= User.find(@race.p6).name %>
</p>

<p>
  <strong>P7:</strong>
  <%= User.find(@race.p7).name %>
</p>

<p>
  <strong>P8:</strong>
  <%= User.find(@race.p8).name %>
</p>

<p>
  <strong>P9:</strong>
  <%= User.find(@race.p9).name %>
</p>

<p>
  <strong>P10:</strong>
  <%= User.find(@race.p10).name %>
</p>

<p>
  <strong>P11:</strong>
  <%= User.find(@race.p11).name %>
</p>

<p>
  <strong>P12:</strong>
  <%= User.find(@race.p12).name %>
</p>

<p>
  <strong>P13:</strong>
  <%= User.find(@race.p13).name %>
</p>

<p>
  <strong>P14:</strong>
  <%= User.find(@race.p14).name %>
</p>

<p>
  <strong>P15:</strong>
  <%= User.find(@race.p15).name %>
</p>

<p>
  <strong>P16:</strong>
  <%= User.find(@race.p16).name %>
</p>

<p>
  <strong>P17:</strong>
  <%= User.find(@race.p17).name %>
</p>

<p>
  <strong>P18:</strong>
  <%= User.find(@race.p18).name %>
</p>

<p>
  <strong>P19:</strong>
  <%= User.find(@race.p19).name %>
</p>

<p>
  <strong>P20:</strong>
  <%= User.find(@race.p20).name %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>