config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
   :controllers => {
    :registrations => "users/registrations"
   }

  resources :races

  resources :grandprix_circuits
  resources :circuits
  resources :grandprixes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'pages/home' => 'high_voltage/pages#show', id: 'home'

  post 'new_grandprix_circuit', to: 'grandprix_circuits#new'

  authenticated :user do
    root 'grandprixes#index', as: :authenticated_root
  end
end

app/models/grandprix.rb
class Grandprix < ApplicationRecord
  belongs_to :user
  has_many :grandprix_circuits, dependent: :destroy
  # has_one_attached :image
end

app/controllers/grandprixes_controller.rb
class GrandprixesController < ApplicationController
  before_action :set_grandprix, only: [:show]
  before_action :set_my_grandprix, only: [:edit, :update, :destroy]

  # GET /grandprixes or /grandprixes.json
  def index
    @grandprixes = Grandprix.all
  end

  def set_my_grandprix
    @grandprix = current_user.grandprixes.find(params[:id])
  end

  # GET /grandprixes/1 or /grandprixes/1.json
  def show
  end

  # GET /grandprixes/new
  def new
    @grandprix = Grandprix.new
  end

  # GET /grandprixes/1/edit
  def edit
  end

  # POST /grandprixes or /grandprixes.json
  def create
    @grandprix = current_user.grandprixes.build(grandprix_params)

    respond_to do |format|
      if @grandprix.save
        format.html { redirect_to grandprix_url(@grandprix), notice: "Grandprix was successfully created." }
        format.json { render :show, status: :created, location: @grandprix }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grandprix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grandprixes/1 or /grandprixes/1.json
  def update
    respond_to do |format|
      if @grandprix.update(grandprix_params)
        format.html { redirect_to grandprix_url(@grandprix), notice: "Grandprix was successfully updated." }
        format.json { render :show, status: :ok, location: @grandprix }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grandprix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grandprixes/1 or /grandprixes/1.json
  def destroy
    @grandprix.destroy

    respond_to do |format|
      format.html { redirect_to grandprixes_url, notice: "Grandprix was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grandprix
      @grandprix = Grandprix.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grandprix_params
      params.require(:grandprix).permit(:name, :description, :id)
    end
end

app/helpers/grandprixes_helper.rb
module GrandprixesHelper
end

app/views/grandprixes/_form.html.erb
<%= form_with(model: grandprix) do |form| %>
  <% if grandprix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grandprix.errors.count, "error") %> prohibited this grandprix from being saved:</h2>

      <ul>
        <% grandprix.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grandprixes/edit.html.erb
<h1>Editing Grandprix</h1>

<%= render 'form', grandprix: @grandprix %>

<%= link_to 'Show', @grandprix %> |
<%= link_to 'Back', grandprixes_path %>

app/views/grandprixes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grand Prix</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grandprixes.each do |grandprix| %>
      <tr>
        <td><%= grandprix.name %></td>
        <td><%= grandprix.description %></td>
        <td><%= link_to 'Show', grandprix %></td>
        <td><%= link_to 'Edit', edit_grandprix_path(grandprix) %></td>
        <td><%= link_to 'Destroy', grandprix, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grandprix', new_grandprix_path %>

app/views/grandprixes/new.html.erb
<h1>New Grandprix</h1>

<%= render 'form', grandprix: @grandprix %>

<%= link_to 'Back', grandprixes_path %>

app/views/grandprixes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @grandprix.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @grandprix.description %>
</p>

<h3>Circuits</h3>

<% @grandprix.grandprix_circuits.each do |gpc| %>
  <p>
    <%= link_to gpc.circuit.name, gpc %>
  </p>

<% end %>

<%= link_to "Add Circuit", new_grandprix_circuit_path(grandprix_id: @grandprix.id) %>

<%= link_to 'Edit', edit_grandprix_path(@grandprix) %> |
<%= link_to 'Back', grandprixes_path %>